### ISSUE TITLE
Add @task decorator

### ISSUE THREAD

**Issue by michalz92** [acivitillo/grizly#183]
This should add the following to the decorated function:
- `@dask.delayed` decorator
- `@retry` decorator
- `@add_method` decorator
- task-level logging (e.g. which task caused the error, task run time, and so on)

It will make the function a method of the Workflow class. 

With this approach, we will be able to more precise log information, as well as raise more specific exceptions for debugging purposes.

**Comment by michalz92** [comment]
Works for delayed and retry; working on logging part.

**Comment by acivitillo** [comment]
Status?

**Comment by michalz92** [comment]
Most of the Dask logic is now hidden in the Extract class. We can come back to if once we have a significant amount of non-extract jobs.
