### ISSUE TITLE
[Enhancement] Progress Bar

### ISSUE THREAD

**Issue by bing9** [acivitillo/grizly#396]
Hi team,

I have come across a very long query that takes forever to run. Would it be possible to use this progress bar? -> By wrapping it on any iterables, we could see the progress when creating/saving q_frames to rds.

`https://github.com/tqdm/tqdm`

Regards,

Bing

**Comment by acivitillo** [comment]
Hi @bing9, I think you can try to do a PR for this. You could try to enhance the `to_df` QFrame method with this. It could be an arg, something like `to_df(show_progress=False)` and you can set to `True` when you want to see the bar.

**Comment by bing9** [comment]
I'll try to do it on 0.4 release.

This involves deep changes in functions to wrap every SQL generator so that nested progress could be visualized.

Regards,

Bing

**Comment by bing9** [comment]
Hi all,

I've done prototype with some dummy process. This is quite easy to use. However, I need to wrap the iterators correctly in grizly. I'll try first and confirm with @malinaa96 .

![image](https://user-images.githubusercontent.com/8092455/81495469-c1b53880-92b0-11ea-8097-1a6c72f545d4.png)


Regards,

Bing

**Comment by bing9** [comment]
Dask is showing the progress bar for tasks. This will be closed.
