### ISSUE TITLE
Speeding up using external tables

### ISSUE THREAD

**Issue by pattrycja96** [acivitillo/grizly#478]
I've created a dashboard connected to the external table and it's not very fast 😢 

- [Example](https://insights.connect.te.com/t/IndustrialSegment/views/10YearsHistory/HistorybyTerritories?iframeSizedToWindow=true&%3Aembed=y&%3AshowAppBanner=false&%3Adisplay_count=no&%3AshowVizHome=no&%3Aorigin=viz_share_link#2) - In that case the data source is also huge.

Can we copy data from external tables to standard tables to check if it helps? Or try to find another solution? 🌷

**Comment by michalz92** [comment]
This is now implemented with `Extract().submit(output_table_type="base")` and new keys in the `output` stanza of `store.json`:
```json
output: {
  "schema_staging": "acoe_spectrum",
  "schema_prod": "data_loads",
  "table_staging": "abc"  # optional, by default extract's name lowercased and underscored (snake case)
  "table_prod": "abc"  # optional, by default the same as table_staging
```
