### ISSUE TITLE
grizly scheduler test coverage

### ISSUE THREAD

**Issue by acivitillo** [acivitillo/grizly#494]
As discussed Marius will be working on increasing grizly test coverage. I have done some research and it seems what we want to do is called `integration testing`. There is a library that allows that kind of testing using docker containers: https://pypi.org/project/pytest-docker/

I also found another library that improves pytest by automatically generating function arguments to test: https://hypothesis.readthedocs.io/en/latest/

When Marius is back from the trainings we can ask for his github username and assign him this issue

**Comment by michalz92** [comment]
I think we need to start with unit tests, so we know the module itself is working properly, then worry about how it interacts with other code.

**Comment by acivitillo** [comment]
How do we test the scheduling?

**Comment by michalz92** [comment]
We can start with a few basic tests: getting connection, adding jobs to triggers, triggers to jobs, etc. Similar as we test QFrame, eg. the S3 class. For now I think we'll be fine with like 10 tests, just make sure we have logs and can retrieve them reasonably.

**Comment by acivitillo** [comment]
Which means we need to run a docker compose in tests.

**Comment by michalz92** [comment]
Yes, we can use Docker-based testing to spin up a temporary environment with Redis instance and workers and test on that environment. But I think the unit tests don't depend on the environment unless they test for that.
