### ISSUE TITLE
Add the possibility for a job to have downstream jobs

### ISSUE THREAD

**Issue by michalz92** [acivitillo/grizly#495]

**Comment by acivitillo** [comment]
Are we doing children workflows or triggered jobs? Normally we would have a trigger: key with a triggered true/false value. Why do we need children workflows?

**Comment by michalz92** [comment]
We need jobs than can trigger other jobs, eg. Sales Weekly should trigger Shipped Shippable.

**Comment by acivitillo** [comment]
Sales weekly would set a `trigger:sales_weekly` to `triggered` which would kick all jobs depending on that trigger.

**Comment by michalz92** [comment]
Okay, so it looks like this?:
```python
shipped_shippable = Job("Shipped Shippable", trigger="Sales Weekly Flash Control Check")
```

**Comment by acivitillo** [comment]
Yes but it should be triggers as now we can support multiple triggers per job.

```python
shipped_shippable.register(triggers="Sales Weekly Flash Control Check")
```

Also this will be possible

```python
shipped_shippable.triggers = "Sales Weekly Flash Control Check"
```
